CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT NOT NULL AUTO_INCREMENT,
  userId BIGINT NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'mention',
  messageId BIGINT NOT NULL,
  channelId BIGINT NOT NULL,
  channelName VARCHAR(100),
  senderId BIGINT NOT NULL,
  senderName VARCHAR(50),
  contentPreview TEXT,
  isRead TINYINT(1) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_userId (userId),
  KEY idx_isRead (isRead),
  KEY idx_createdAt (createdAt),
  CONSTRAINT fk_notifications_user FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_notifications_message FOREIGN KEY (messageId) REFERENCES messages (id) ON DELETE CASCADE,
  CONSTRAINT fk_notifications_channel FOREIGN KEY (channelId) REFERENCES channels (id) ON DELETE CASCADE,
  CONSTRAINT fk_notifications_sender FOREIGN KEY (senderId) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
